### ISSUE TITLE
Antenn rikting

### ISSUE THREAD

**Issue by Poppe66** [MoveAlongNothingToSeeHere/Ruthless#16]
https://github.com/MoveAlongNothingToSeeHere/Ruthless/blob/1aa2474d0172d09ef9f4550ef7b7a9122f2c8e40/Eden%20Settings#L212

Något som är immersive eller medför fler problem? Antenn riktning kanske spökar med ace?

**Comment by AVESUM** [comment]
Detta visar att karaktärer talar genom att göra en liten våglängdskurva över nametag.
