### ISSUE TITLE
Advanced balistics 

### ISSUE THREAD

**Issue by Poppe66** [MoveAlongNothingToSeeHere/Ruthless#6]
https://github.com/MoveAlongNothingToSeeHere/Ruthless/blob/6d734161532353b5063f2fdfe9aa8456e67c50ca/Eden%20Settings#L1

Gäller detta alla vapen? Jag tänker att om en KSP ska göra alla dessa beräkningar kommer servern gå på knä snabbare än utan. Något vi kan ha på basic?

**Comment by Poppe66** [comment]
Skall testas utan

**Comment by AVESUM** [comment]
Klart
