### ISSUE TITLE
Toolkit

### ISSUE THREAD

**Issue by Poppe66** [MoveAlongNothingToSeeHere/Ruthless#8]
https://github.com/MoveAlongNothingToSeeHere/Ruthless/blob/6d734161532353b5063f2fdfe9aa8456e67c50ca/Eden%20Settings#L241

Kommer kräva att piloterna har toolkit i ryggan för att Kitta gripen eller liknande vilket betyder att dom måste ha en ryggsäck.

**Comment by Poppe66** [comment]
Ska plockar bort

**Comment by AVESUM** [comment]
Klart
