### ISSUE TITLE
Fordons lås 

### ISSUE THREAD

**Issue by Poppe66** [MoveAlongNothingToSeeHere/Ruthless#9]
https://github.com/MoveAlongNothingToSeeHere/Ruthless/blob/6d734161532353b5063f2fdfe9aa8456e67c50ca/Eden%20Settings#L336

Är detta något vi aktivt kommer använda? eller kommer vi öppna låsen vid OP start och sen strunta i det?

**Comment by Poppe66** [comment]
Kollar med grupperna efter söndags OP 15/4 -2018

**Comment by AVESUM** [comment]
Vi testar ett tag till med fordonen uppmärkta, därefter utvärderar vi igen
